services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: financeuser
      POSTGRES_PASSWORD: financepass
      POSTGRES_DB: personal_finance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financeuser -d personal_finance"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://financeuser:financepass@db:5432/personal_finance
      - SECRET_KEY=your-secret-key-for-development
      - POSTGRES_HOST=db
      - POSTGRES_USER=financeuser
      - POSTGRES_PASSWORD=financepass
      - POSTGRES_DB=personal_finance
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["bash", "/app/entrypoint.sh"]

volumes:
  postgres_data: 